<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>psm</string>
		<string>psh</string>
	</array>
	<key>name</key>
	<string>Picoblaze Assembly</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>;.*$</string>
			<key>name</key>
			<string>comment.line</string>
			<key>foreground</key>
			<string>#EEEEEE</string>
		</dict>
		<dict>
			<key>match</key>
			<string>//.*$</string>
			<key>name</key>
			<string>comment.line</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\.(BUF|BYT|END|EQU|FI|IF|ORG|SCR|TXT)</string>
			<key>name</key>
			<string>support.type.psm</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.psm</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.psm</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.include.psm</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b\d+'b</string>
			<key>name</key>
			<string>constant.numeric.bin</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b\d+'d</string>
			<key>name</key>
			<string>constant.numeric.dec</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b\S+'[upper|lower]</string>
			<key>name</key>
			<string>constant.numeric.dec</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.psm</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.psm</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.include.psm</string>
		</dict>
		<dict>
			<key>match</key>			
			<string>\b(ADD|ADDCY|AND|CALL|COMPARE|DISABLE|ENABLE|FETCH|INPUT|JUMP|LOAD|OR|OUTPUT|RETURN|RETURNI|RL|RR|SL0|SL1|SLA|SLX|SR0|SR1|SRA|SRX|STORE|SUB|SUBCY|TEST|XOR|CALL@|COMPARECY|HWBUILD|JUMP@|LOAD&RETURN|OUTPUTK|REGBANK|STAR|TESTCY)\b</string>
			<key>name</key>
			<string>support.function</string>
		</dict>
		<dict>
			<key>match</key>			
			<string>\b(STRING|INCLUDE|ADDRESS|CONSTANT)\b</string>
			<key>name</key>
			<string>entity.name.function.macro</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[0-9a-fA-F]+\b</string>
			<key>name</key>
			<string>variable.other.constant</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b0b[0-1]+\b</string>
			<key>name</key>
			<string>constant.numeric.bin</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(s[0-9A-Fa-f]|Z|NZ|C|NC)\b</string>
			<key>name</key>
			<string>keyword</string>
		</dict>		
	</array>
	<key>scopeName</key>
	<string>source.psm</string>
	<key>uuid</key>
	<string>7e391fa0-da13-4091-ab1b-17f37c027a56</string>
</dict>
</plist>
